# Generated by gencrud
# field user.U_ACTIVE constants

C_U_ACTIVE_MAPPING = {True: 'Yes', False: 'No'}


# field user.U_MUST_CHANGE constants

C_U_MUST_CHANGE_MAPPING = {True: 'Yes', False: 'No'}


# field user.U_LISTITEMS constants
C_U_LISTITEMS__5_RECORDS                                         = 5
C_U_LISTITEMS__10_RECORDS                                        = 10
C_U_LISTITEMS__25_RECORDS                                        = 25
C_U_LISTITEMS__100_RECORDS                                       = 100

C_U_LISTITEMS_MAPPING = {5: '5 Records', 10: '10 Records', 25: '25 Records', 100: '100 Records'}


