#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2023-01-07 16:14:56 version 2.3.707 by user W124574
#
import webapp.api as API
from marshmallow import fields, post_dump


class AccessRefSchema( API.mm.SQLAlchemySchema ):
    """Schema for the te_test_tree_ref table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    AR_ID    = fields.Integer()
    AR_A_ID    = fields.Integer()
    AR_R_ID    = fields.Integer()
    AR_INDEX    = fields.Integer()

    __field_set__ = {
        'AR_ID': 0,
        'AR_A_ID': 0,
        'AR_R_ID': 0,
        'AR_INDEX': 0,
    }

    @post_dump
    def post_dump_process( self, in_data, **kwargs ):
        for field, default in self.__field_set__.items():
            if in_data[ field ] is None:
                in_data[ field ] = default

        return in_data


access_refSchema   = AccessRefSchema()
access_refsSchema  = AccessRefSchema( many = True )
